sura-sang/xr_project

- Assets/Scripts/CharacterMove/MoveStates/CharacterMoveGrounded.cs
앉기 기능 비활성화
그냥 앉기 들어가는 부분만 주석처리 했습니다.
> 앉기 기능 비활성화

- .gitignore
- .idea/.idea.xr_project/.idea/projectSettingsUpdater.xml
- .idea/.idea.xr_project/.idea/workspace.xml
**깃 이그노어에 ds_store 추가**
맥 파일 시스템을 사용하면 자동으로 생성되는 파일 이그노어 처리
**라이더 관련 설정 추가**
젯브레인 라이더 설정들 추가
> 깃 이그노어에 ds_store 추가 (맥 관련 파일), 라이더 관련 설정 추가

- Assets/_Resources/_update/Effect/Materials/MEffect_ang.meta
- Assets/_Resources/_update/Effect/Materials/MEffect_joy.meta
- Assets/_Resources/_update/Effect/Materials/MEffect_sad.meta
- Assets/_Resources/_update/Effect/Models/SMEffect_ang.meta
- Assets/_Resources/_update/Effect/Models/SMEffect_joy.meta
- Assets/_Resources/_update/Effect/Models/SMEffect_sad.meta
- Assets/_Resources/_update/Effect/Prefab/PREffect_ang.meta
- Assets/_Resources/_update/Effect/Prefab/PREffect_joy.meta
- Assets/_Resources/_update/Effect/Prefab/PREffect_sad.meta
- Assets/_Resources/_update/Effect/Shaders/SEffect_ang.meta
- Assets/_Resources/_update/Effect/Shaders/SEffect_joy.meta
- Assets/_Resources/_update/Effect/Shaders/SEffect_sad.meta
- Assets/_Resources/_update/Effect/Textures/TEffect_ang.meta
- Assets/_Resources/_update/Effect/Textures/TEffect_joy.meta
- Assets/_Resources/_update/Effect/Textures/TEffect_sad.meta
> 이펙트 파일 저장양식파일 업로그

- Assets/Scenes/InteractionTestScene.unity
- Assets/Scripts/Player/PlayerState/PlayerMoveGrounded.cs
- Assets/Scripts/Skill.meta
- Assets/Scripts/Skill/AngerSkill.cs
- Assets/Scripts/Skill/AngerSkill.cs.meta
**분노 스킬 구현**
Script/Skill 폴더 내 AngerSkill.cs 파일 생성해서 구현했습니다.
하드코딩하고 InteractionTestScene 내부 PlayerDummy 오브젝트에 컴포넌트 달아줬습니다.
Coroutine으로 스킬 지속시간 관리하고 Ray로 전방에 물체 감지합니다.
회전 각을 Min, Max로 빼서 스킬 사용 중 회전할 수 있는 각을 제한합니다.
**수정 사항**
PlayerMoveGrounded 상태에서 UpdateState문에 캐릭터 Speed 갱신 코드를 추가했습니다.
AngSkill.cs 에서 플레이어 Speed를 직접 가져와서 사용 시에 1.0f으로 갱신하도록 수정했습니다.
**오류 사항**
플레이어 스킬 사용 시 오브젝트 떨림 현상이 있는데 Cinemachine 카메라 문제인 것으로 확인했습니다.
이동 관련 로직은 오류 없습니다.
> 캐릭터 분노 스킬(AngerSkill) 시스템

- Assets/_Resources/_update.meta
- Assets/_Resources/_update/Dummy.meta
- Assets/_Resources/_update/Dummy/Animations.meta
- Assets/_Resources/_update/Dummy/Models.meta
- Assets/_Resources/_update/Effect.meta
- Assets/_Resources/_update/Effect/Materials.meta
- Assets/_Resources/_update/Effect/Materials/MEffect_ang.meta
- Assets/_Resources/_update/Effect/Prefab.meta
- Assets/_Resources/_update/Effect/Prefab/PREffect_ang.meta
- Assets/_Resources/_update/Effect/Shaders.meta
- Assets/_Resources/_update/Effect/Shaders/SEffect_ang.meta
- Assets/_Resources/_update/Effect/Textures.meta
- Assets/_Resources/_update/Effect/Textures/TEffect_ang.meta
> _update 폴더 제거

- Assets/_Resources/_update.meta
- Assets/_Resources/_update/Dummy.meta
- Assets/_Resources/_update/Dummy/Animations.meta
- Assets/_Resources/_update/Dummy/Models.meta
- Assets/_Resources/_update/Effect.meta
- Assets/_Resources/_update/Effect/Materials.meta
- Assets/_Resources/_update/Effect/Materials/MEffect_ang.meta
- Assets/_Resources/_update/Effect/Prefab.meta
- Assets/_Resources/_update/Effect/Prefab/PREffect_ang.meta
- Assets/_Resources/_update/Effect/Shaders.meta
- Assets/_Resources/_update/Effect/Shaders/SEffect_ang.meta
- Assets/_Resources/_update/Effect/Textures.meta
- Assets/_Resources/_update/Effect/Textures/TEffect_ang.meta
Reverts sura-sang/xr_project#52
> Revert "_update 폴더 제거"

- Assets/Scenes/1Stage.unity
- Assets/Scenes/1Stage/Global Volume Profile.asset
- Assets/Scenes/1Stage/Global Volume Profile.asset.meta
- Assets/Scenes/1Stage/Lens Flare.asset
- Assets/Scenes/1Stage/Lens Flare.asset.meta
- ProjectSettings/ProjectSettings.asset
- ProjectSettings/TagManager.asset
**URP PP Volume 추가**
메인 카메라에서 사용할 후처리 효과들 오버라이딩 시켜놨습니다.
Bloom, Lift Gamma Gain, Split Toning, DOF를 사용하고, SRP는 추후에 사용할 수 있으면 사용할 예정입니다.
모든 수치 값들은 그레이박싱 이후 실제로 메시 올리고 재질작업 다 끝났을 때 다시 작업합니다.
일단은 임시로 조절해 놨습니다.
> 카메라 PP 후처리 임시 추가

- Assets/Scenes/InteractionTestScene.unity
- Assets/Scripts/Monster/Anger.cs
- Assets/Scripts/Monster/MonsterState/Anger/AngerChase.cs
- Assets/Scripts/Monster/MonsterState/Anger/AngerChase.cs.meta
- Assets/Scripts/Monster/MonsterState/Anger/AngerDash.cs
- Assets/Scripts/Monster/MonsterState/Anger/AngerDash.cs.meta
- Assets/Scripts/Monster/MonsterState/Anger/AngerIdle.cs
- Assets/Scripts/Monster/MonsterState/Anger/AngerIdle.cs.meta
**분노 몬스터 스킬 개발**
상태 3개 추가
기본 -> 추격 -> 대쉬(공격 스킬)
> 분노 몬스터 스킬 개발

- Assets/Scripts/Monster/Monster.cs
- Assets/Scripts/Player/Player.Absorb.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveFalling.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveGrounded.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveHolding.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveJumping.cs
- Assets/Scripts/Player/PlayerState/PlayerUseSkill.cs
- Assets/Scripts/Skill/AngerSkill.cs
- Assets/Scripts/Skill/HappySkill.cs
- Assets/_Resources/Characters/Monster/Animations/AC_Anger.controller
- Assets/_Resources/Characters/Monster/Animations/AC_Anger.controller.meta
- Assets/_Resources/Characters/Monster/Animations/AC_Happy.controller
- Assets/_Resources/Characters/Monster/Animations/AC_Happy.controller.meta
- Assets/_Resources/Characters/Monster/Animations/AC_Sad.controller
- Assets/_Resources/Characters/Monster/Animations/AC_Sad.controller.meta
- Assets/_Resources/Characters/Player/Animations/AC_Player.controller
- Assets/_Resources/Characters/Player/Animations/AC_Player.controller.meta
- Assets/_Resources/Characters/Player/Animations/Empty.anim
- Assets/_Resources/Characters/Player/Animations/Empty.anim.meta
**플레이어 애니메이션 컨트롤러 - AC_Player**
이동, 점프, 매달리기, 스킬 사용에 따른 애니메이션 State 세팅했습니다.
bool 타입의 IsFalling, IsJumping, IsHolding, IsUseSkill 파라미터를 사용하고
float 타입의 Speed, Emotion, Forward, Left 파라미터를 사용합니다.
플레이어 Emotion 상태에 따른 애니메이션 세팅을 위해 블렌더 트리를 사용하여 관리하고
Holding 같은 경우도 위, 좌, 우를 Forward, Left 파라미터를 사용해 블렌더 트리로 바뀌게 끔 해놨습니다.
현재 애니메이션 클립이 없는 경우 Empty 클립을 넣어놨고 흡수 관련한 애니메이션이 추가로 들어간다고 해서
그 부분은 타이밍 관련 회의 끝나고 스크립트 수정과 함께 이루어 질 것 같아 미리 PR 요청합니다!
> Player 애니메이션 컨트롤러 세팅

- Assets/Scenes/1Stage_BJY.unity
- Assets/Scripts/Skill/AngerSkill.cs
- Assets/Scripts/Skill/HappySkill.cs
- Assets/_Resources/Characters/Player/Animations/AC_Player.controller
- Assets/_Resources/Characters/Player/Animations/A_P_common_AB.anim
- Assets/_Resources/Characters/Player/Animations/A_P_empty_IDLE1.anim
- Assets/_Resources/Characters/Player/Animations/A_P_empty_IDLE2.anim
- Assets/_Resources/Characters/Player/Animations/A_P_empty_IDLE3.anim
- Assets/_Resources/Characters/Player/Animations/A_P_empty_RUN.anim
- Assets/_Resources/Characters/Player/Animations/A_P_empty_WALK.anim
- Assets/_Resources/Characters/Player/Animations/A_P_sad_IDLE.anim
- Assets/_Resources/Characters/Player/Animations/A_P_sad_SKILL.anim
- Assets/_Resources/Characters/Player/Animations/A_P_sad_WALK 1.anim
- ProjectSettings/DynamicsManager.asset
- ProjectSettings/QualitySettings.asset
- ProjectSettings/TagManager.asset
> 씬 기본 구성요소 세팅

- .gitignore
- Assets/PaidAssets.meta
> 깃 이그노어 경로 수정

- Assets/_Resources/Effect/Prefab/PREffect_sad/E_BG_PREffect_MOP_01.prefab
- Assets/_Resources/Effect/Prefab/PREffect_sad/E_BG_PREffect_MOP_01.prefab.meta
- Assets/_Resources/Effect/Prefab/PREffect_sad/E_BG_PREffect_MOP_1010.prefab
- Assets/_Resources/Effect/Prefab/PREffect_sad/E_BG_PREffect_MOP_1010.prefab.meta
- Assets/_Resources/Effect/Shaders/SEffect_sad/SEffect_sad_bg_MOP_01.shader
- Assets/_Resources/Effect/Shaders/SEffect_sad/SEffect_sad_bg_MOP_01.shader.meta
- Assets/_Resources/Effect/Shaders/SEffect_sad/SEffect_sad_bg_MOP_02.shader
- Assets/_Resources/Effect/Shaders/SEffect_sad/SEffect_sad_bg_MOP_02.shader.meta
> 버섯포자 이펙트 제출

- Assets/_Resources/Effect/Materials/MEffect_sad/MEffect_BG_01.mat
- Assets/_Resources/Effect/Materials/MEffect_sad/MEffect_BG_01.mat.meta
- Assets/_Resources/Effect/Materials/MEffect_sad/MEffect_BG_02.mat
- Assets/_Resources/Effect/Materials/MEffect_sad/MEffect_BG_02.mat.meta
> 버섯포자 이펙트 제출2

- Assets/Scripts/Player/Player.cs
- Assets/_Resources/Characters/Player/Animations/AC_Player.controller
- Assets/_Resources/Characters/Player/Animations/A_P_common_DRINK.anim
- Assets/_Resources/Characters/Player/Animations/A_P_common_HANG.fbx.meta
- Assets/_Resources/Characters/Player/Animations/A_P_common_JUMP.fbx.meta
**AC_Player 구조 수정**
기존 구조는 같으나 흡수 -> 변신 과정이 추가되어서 이에 따른 State 추가했습니다.
Empty 처리되었던 몇몇 애니메이션들 엔진에 올라와 있는걸로 교체했고, Jump <-> Fall 타이밍 수정했습니다.
> 플레이어 애니메이선 컨트롤러 수정

- Assets/Scenes/InteractionTestScene.unity
- Assets/_Resources/Prefabs/Log.prefab
**통나무가 양쪽으로 넘어갈 수 있던 문제 수정**
힌지 조인트 파라미터 수정으로 해결
Limits 와 Moter 값 세팅
**인터렉션 씬 정상화**
- 게임 매니저 내용이 없어서 생기던 오류 해결
- 시작지점, 퍼즐 요소 위치 약간 수정
> 통나무가 양쪽으로 넘어가던 현상 수정

- Assets/Scripts/EventSystem/EventManager.cs
- Assets/Scripts/EventSystem/Events/ObjectActivateArea.cs
- Assets/Scripts/EventSystem/Events/ObjectActivateArea.cs.meta
**활성화/비활성화 이벤트**
급작스럽게 요구해서 추가된 이벤트입니다.
단순하게 구역에 들어가면 오브젝트 껐다 켰다 하는 겁니다.
트리거 추가하고 ObjectActivateArea 스크립트 넣고 활성화/비활성화 할 Object들을 넣어주면 됩니다.
> 오브젝트 활성화 이벤트 추가

- Assets/_Resources/Characters/Monster/Animations/AC_Amanita.Happy.controller
- Assets/_Resources/Characters/Monster/Animations/AC_Amanita.Sad.controller
- Assets/_Resources/Characters/Monster/Animations/AC_Macrolepiota.controller
- Assets/_Resources/Characters/Monster/Animations/AC_Matsutake.Anger.controller
- Assets/_Resources/Characters/Monster/Animations/AC_Matsutake.Sad.controller
- Assets/_Resources/Characters/Player/Animations/AC_Player.controller
**Player**
AC_Player 애니메이터의 RunJump 항목 클립을 기본 점프와 동일하게 변경했습니다.
**AI**
버섯 AI들 클립을 애니메이터에 적용했습니다.
A_MS1_common_AB - 새송이버섯 흡수
A_MS1_command_SLEEP - 새송이버섯 잠
A_MS1_ang_IDEL - 분노 새송이버섯 기본
A_MS1_ang_WALK - 분노 새송이버섯 걷기
A_MS2_sad_WALK - 갓버섯 걷기
A_MS3_common_SLEEP - 광대버섯 잠
A_MS3_common_POP - 광대버섯 인터렉션 ( 밟힌거 )
A_MS_2_sad_WALK - 슬픔 광대버섯 걷기
A_MS3_joy_WALK - 기쁨 광대버섯 걷기
> AI 애니메이터 클립 적용

- Assets/NewLayer.terrainlayer
- Assets/NewLayer.terrainlayer.meta
- Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
- Assets/_Resources/3D_Background/Sbsar/NewLayer.terrainlayer
- Packages/manifest.json
- Packages/packages-lock.json
> Terrain Tool 다운그레이드

- Assets/Scripts/Player/PlayerState/PlayerMoveGrounded.cs
- Assets/_Resources/Characters/Player/Animations/AC_Player.controller
grounded 상태에서 onrun을 제대로 저장하지 않던 문제 수정
플레이어 애니메이터 연결 조건 수정
- 달리기 -> 걷기 조건에 이동속도 제거
- 달리기 -> 아이들 로 이동하는 트랜지션 추가 (속도 관련)
> 달리기 애니메이션 버그 수정

- Assets/Resources/SO/Player Data.asset
- Assets/Scripts/GameData/SO/PlayerData.cs
- Assets/Scripts/Player/Player.Input.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveJumping.cs
**-현재 버튼 상태 가져오기-**
`GetActionValue(ButtonActions type)`
**-달리면서 점프할 때 추가 값 적용하는 기능 추가-**
> 달리기 점프 기능 추가

- Assets/Resources/SO/Player Data.asset
- Assets/Scripts/Player/PlayerState/PlayerMoveFalling.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveJumping.cs
- Assets/_Resources/Characters/Player/Animations/AC_Player.controller
- Assets/_Resources/Prefabs/Player.prefab
**플레이어 애니메이터 버그 수정**
- 달리면서 점프 할 때 허공답보하던 버그
- 가끔 jump 상태에서 idle로 내려오지 못하는 버그
**플레이어 프리팹에 슬픔 모델 추가**
- 사라진 눈 추가
**공중에서 방향 조절 기능 수정**
공중에서 방향 조절하는 기능 때문에 공중에서 추진력을 잃던 버그 수정
> 플레이어 버그 수정

- Assets/Scripts/Audio.meta
- Assets/Scripts/Audio/ScriptUsageBasic.cs
- Assets/Scripts/Audio/ScriptUsageBasic.cs.meta
> 사운드 스크립트 예제 첨부

- Assets/Scenes/SoundTest.unity
- Assets/Scripts/Audio/AudioManager.cs
- Assets/Scripts/Audio/AudioManager.cs.meta
- Assets/Scripts/Player/Player.Absorb.cs
- Assets/Scripts/Player/Player.StepSound.cs
흡수 시에 사운드 바인딩 해놨습니다.
오디오 매니저에 모든 이벤트 전부 인스펙터로 링크하고 추후에 쓸 함수들 더 추가할 예정입니다.
머지해달라고 하셔서 pr 올려요
> 플레이 흡수 사운드 및 오디오 매니저 구성

- Assets/Scenes/SoundTest.unity
- Assets/Scripts/Audio/AudioManager.cs
- Assets/Scripts/Audio/AudioUIPlayer.cs
- Assets/Scripts/Audio/AudioUIPlayer.cs.meta
- Assets/Scripts/Monster/MonsterState/Common/MonsterMoveSleep.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveGrounded.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveHolding.cs
- Assets/Scripts/Skill/AngerSkill.cs
- Assets/Scripts/Skill/HappySkill.cs
- Assets/Scripts/Skill/SadSkill.cs
- ProjectSettings/EditorBuildSettings.asset
UI 버튼 Enter, Click
PreeAnyKey 화면에서 게임 시작 전 화면으로 가는 사운드
BGM이 Instance로 관리되어 메인화면부터 끊기지 않음
SkillHelper Open 사운드
및 크레딧 창에서 사용할 EQ 파라미터 조절
> UI, EQ, BGM 인스턴스 관리 및 테스트 씬 수정

- Assets/Scripts/Audio/AudioManager.cs
기존 Object 상태에 따라 Load(), Unload() 로 관리하던거 재시작시에 버그생겨서
Instance로 게임 죽을 때 까지 관리하게 바꿈
> Bank 파일 로드 버그 수정

- Assets/Resources/Effect/BG_CGPREFAB/===bgeffect_firefly.prefab
- Assets/Resources/Effect/BG_CGPREFAB/===bgeffect_firefly.prefab.meta
- Assets/Resources/Effect/BG_CGPREFAB/===bgeffect_soap.prefab
- Assets/Resources/Effect/BG_CGPREFAB/===bgeffect_soap.prefab.meta
> 진짜 최종최종 배치 도비는 진짜 자유입니다

- Assets/_Resources/Effect/Materials/MEffect_sad/M_Additve ANG.mat
- Assets/_Resources/Effect/Materials/MEffect_sad/M_Additve ANG.mat.meta
- Assets/_Resources/Effect/Materials/MEffect_sad/M_Additve JOY.mat
- Assets/_Resources/Effect/Materials/MEffect_sad/M_Additve JOY.mat.meta
- Assets/_Resources/Effect/Materials/MEffect_sad/M_Additve SAD.mat
- Assets/_Resources/Effect/Materials/MEffect_sad/M_Additve SAD.mat.meta
- Assets/_Resources/Effect/Shaders/SEffect_sad/S_Additve ANG.shader
- Assets/_Resources/Effect/Shaders/SEffect_sad/S_Additve ANG.shader.meta
- Assets/_Resources/Effect/Shaders/SEffect_sad/S_Additve JOY.shader
- Assets/_Resources/Effect/Shaders/SEffect_sad/S_Additve JOY.shader.meta
- Assets/_Resources/Effect/Shaders/SEffect_sad/S_Additve SAD.shader
- Assets/_Resources/Effect/Shaders/SEffect_sad/S_Additve SAD.shader.meta
> 이펙트 아웃라인 이펙트..

- Assets/Scripts/Monster/Monster.cs
- Assets/Scripts/Player/Player.Absorb.cs
몬스터 스크립트에서 IsAbsorbAble 끄면 흡수할 수 없게 함
> 흡수 가능여부 선택 기능 추가

- Assets/Scripts/Core/CharacterMove/CharacterMove.cs
- Assets/Scripts/Monster/MonsterState/Anger/AngerReady.cs
- Assets/Scripts/PuzzleSystem/Direction/PuzzleTrampolin.cs
- Assets/Scripts/PuzzleSystem/Grow/PuzzleClown.cs
- Assets/Scripts/PuzzleSystem/PuzzleElements.cs
**분노 준비 중 플레이어를 바라보지 않던 문제 수정
트램폴린 버섯 커지기 전에 사용할 수 있던 문제 수정**
> 몬스터 관련 버그들

- Assets/Scripts/Core/Global.cs
- Assets/Scripts/PuzzleSystem/Direction/Editor/PuzzleTrampolinEditor.cs
플레이어 데이터를 가져오지 못하던 문제 수정
Play중이 아닐 때 UIManager를 생성하려던 문제 수정
> 트램폴린 에디터 에러 수정

- Assets/_Resources/Characters/Player/Animations/AC_Player.controller
분노 몬스터한테 맞으면 카메라 스위치 안되는거 Any State로 진입해서 그런 것 같습니다.
그래서 Idle, Walk, Run에서 진입하게 수정했습니다.
> Hit 애니메이션 진입 조건 수정

- Assets/Scenes/TitleScene.unity
- Assets/Scripts/Audio/AudioManager.cs
- Assets/Scripts/Audio/AudioTrigger.cs
- Assets/Scripts/Audio/AudioTrigger.cs.meta
- Assets/Scripts/EventSystem/Events/MoveShapeTrigger.cs
- Assets/Scripts/EventSystem/Events/TimelineController.cs
- Assets/Scripts/Player/Player.Absorb.cs
- Assets/Scripts/Player/Player.StepSound.cs
- Assets/Scripts/Player/Player.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveJumping.cs
- Assets/Scripts/Skill/HappySkill.cs
- Assets/Scripts/TitleScene/TitleScene.cs
- Assets/_Resources/3D_Background/Jamiwa/Prefabs/PR_Jamiwa.prefab
- Assets/_Resources/3D_Background/Prefabs/Sub_Object/PR_PuzzleBoard_Sub.prefab
- Assets/_Resources/Prefabs/Player.prefab
씬에 환경음 배치 및 발소리를 위해 오브젝트들 레이어 변경
> 씬에 환경음 배치 및 발소리를 위해 오브젝트들 레이어 변경

- Assets/Scripts/Audio/AudioManager.cs
- Assets/Scripts/EventSystem/Events/MoveShape.cs
- Assets/Scripts/Player/Player.StepSound.cs
- Assets/Scripts/Player/Player.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveGrounded.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveJumping.cs
> 오브젝트 SFX 기능 추가 및 버그

- Assets/Settings/ForwardRenderer.asset
- Assets/_Resources/3D_Background/Decal/M_Decal/M_Decal_Arrow.mat
- Assets/_Resources/3D_Background/Decal/M_Decal/M_Decal_FootPlate.mat
- Assets/_Resources/3D_Background/Decal/M_Decal/M_Decal_Jump.mat
- Assets/_Resources/3D_Background/Decal/M_Decal/M_Decal_Mushroom_Jump.mat
- Assets/_Resources/3D_Background/Decal/M_Decal/M_Decal_WoodBump.mat
- Assets/_Resources/3D_Background/Decal/M_Decal/M_Decal_X.mat
> 데칼 해결 한별쨩 땡큐

- Assets/Scripts/Monster/MonsterState/Sadness/SadnessIdle.cs
- Assets/Scripts/Skill/HappySkill.cs
> 기쁨스킬 페이드아웃버그, 슬픔이 안따라오는 버그

- Assets/Resources/Effect/BG_CGPREFAB/===bgwaterfall.prefab
- Assets/_Resources/Effect/BG_WATERFALL/PR/E_BG_PR_WATERFALL.prefab
- Assets/_Resources/Effect/Materials/MEffect_sad/MEffect_waf.mat
- Assets/_Resources/Effect/Materials/MEffect_sad/MEffect_waf.mat.meta
- Assets/_Resources/Effect/Shaders/SEffect_sad/SEffect_Sad_waf.shader
- Assets/_Resources/Effect/Shaders/SEffect_sad/SEffect_Sad_waf.shader.meta
> 수정수정 이펙트 수정

- Assets/DO_Effect/PREffect_sad/E_BG_PR_FALL.prefab
> 이펙트 수정 최종이길

- Assets/Scripts/Audio/AudioManager.cs
- Assets/Scripts/Monster/MonsterState/Anger/AngerDash.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveHolding.cs
- Assets/Scripts/Skill/SadSkill.cs
> 사용하지 않는 사운드로 버그 발생해서 삭제

- Assets/Scripts/Audio/AudioManager.cs
- Assets/Scripts/Audio/AudioTrigger.cs
- Assets/Scripts/Player/Player.StepSound.cs
- Assets/Scripts/PuzzleSystem/Direction/PuzzleTrampolin.cs
- Assets/Scripts/Save/SceneMaster.cs
> 재시작시 사운드 초기화 버그랑 이것저것

- Assets/Scripts/Player/Player.Input.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveGrounded.cs
- Assets/Scripts/Skill/AngerSkill.cs
- Assets/_Resources/Dummy/Prefabs/Dummy/CheckPoint.prefab
분노 스킬 사용 할 때 충돌하는 애니메이션이 재생되던 문제
버튼을 계속 누르고 있으면 분노 스킬을 연속으로 사용할 수 있던 문제
체크포인트 영역에 충돌하는 문제
> 분노 스킬 관련 버그

- Assets/Scripts/EventSystem/Events/MoveShapeTrigger.cs
- Assets/Scripts/Player/Player.StepSound.cs
> 레이어 두개 이상일 때 발판 고장나는 버그 수정

- Assets/New Render Texture.renderTexture
- Assets/New Render Texture.renderTexture.meta
- Assets/Scripts/Audio/AudioManager.cs
- Assets/Scripts/EventSystem/Events/EndingEvent.cs
- Assets/Scripts/EventSystem/Events/EndingEvent.cs.meta
- Assets/_Resources/Characters/Player/Animations/AC_Player.controller
- Assets/_Resources/Video/FadeImg.anim
- Assets/_Resources/Video/FadeImg.anim.meta
- Assets/_Resources/Video/FadeImg.controller
- Assets/_Resources/Video/FadeImg.controller.meta
> 엔딩 컷씬 이벤트 추가

- Assets/New Render Texture 1.renderTexture
- Assets/New Render Texture 1.renderTexture.meta
- Assets/Scenes/TitleScene.unity
- Assets/Scripts/Audio/AudioManager.cs
- Assets/Scripts/EventSystem/Events/EndingEvent.cs
- Assets/Scripts/Player/Player.StepSound.cs
- Assets/Scripts/TitleScene/TitleScene.cs
- Assets/_Resources/Title/UI_Animator.controller
- Assets/_Resources/Title/UI_CreditOff.anim
- Assets/_Resources/Title/UI_CreditOff.anim.meta
- Assets/_Resources/Title/UI_CreditOn.anim
- Assets/_Resources/Title/UI_CreditOn.anim.meta
- Assets/_Resources/Video/FadeImg.anim
- Assets/_Resources/Video/RawImage.controller
- Assets/_Resources/Video/RawImage.controller.meta
- Assets/_Resources/Video/RawImg.anim
- Assets/_Resources/Video/RawImg.anim.meta
- Assets/_Resources/Video/credit.mp4.meta
- Assets/_Resources/Video/outro.mp4.meta
- ProjectSettings/TagManager.asset
> 타이틀 크레딧 & 백타이틀 & 엔딩 컷씬

- Assets/Scripts/Audio/AudioManager.cs
- Assets/Scripts/Audio/AudioTrigger.cs
- Assets/Scripts/EventSystem/Events/EndingEvent.cs
- Assets/Scripts/Save/SceneMaster.cs
- Assets/Scripts/Skill/HappySkill.cs
- ProjectSettings/TagManager.asset
> 전체적인 버그 수정

- Assets/Resources/UI/Panel/TimelineSkipPanel.prefab
- Assets/Resources/UI/Panel/TimelineSkipPanel.prefab.meta
- Assets/Resources/UIManager.prefab
- Assets/Scripts/EventSystem/Events/TimelineController.cs
- Assets/Scripts/Player/Player.Input.cs
- Assets/Scripts/Player/Player.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveGrounded.cs
- Assets/Scripts/Save/SceneMaster.cs
- Assets/Scripts/UI/UITimelineSkipPanel.meta
- Assets/Scripts/UI/UITimelineSkipPanel/UITimelineSkipPanel.cs
- Assets/Scripts/UI/UITimelineSkipPanel/UITimelineSkipPanel.cs.meta
- Assets/_Resources/Puzzle/TimeLine.playable
canmove 조건을 아예 움직이지 못하는 것 에서 인풋만 막도록 수정
타임라인 스킵 기능 추가
> 타임라인 스킵 기능 추가

- Assets/Scripts/Audio/AudioManager.cs
- Assets/Scripts/EventSystem/Events/MoveShapeTrigger.cs
- Assets/Scripts/Monster/MonsterState/MonsterMoveState.cs
- Assets/Scripts/Monster/MonsterState/Sadness/SadnessIdle.cs
- Assets/Scripts/Player/PlayerState/PlayerMoveJumping.cs
> 빌드 에러 using 지시문 제거

- Assets/Scenes/TitleScene.unity
> 크레딧 검은화면 추가

- Assets/Scripts/Audio/AudioManager.cs
- Assets/Scripts/Audio/AudioTrigger.cs
- Assets/Scripts/Save/SceneMaster.cs
> 재시작 시 배경음도 같이 꺼지는 것 수정
